# Generated by Django 5.2.7 on 2025-10-29 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='La dirección contiene caracteres no permitidos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑüÜ\\s,.\\-#°]+$'), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='distrito',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El distrito solo puede contener letras, espacios y guiones.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 dígitos numéricos.', regex='^\\d{8}$'), django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 9 y 15 dígitos. Puede incluir + al inicio.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
