# Generated by Django 5.2.7 on 2025-10-29 18:12

import denuncias_service.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_service', '0004_alter_denuncia_status_denunciaevidencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Denuncia', 'verbose_name_plural': 'Denuncias'},
        ),
        migrations.AlterModelOptions(
            name='denunciaevidencia',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidence'},
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='La descripción contiene caracteres no permitidos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑüÜ\\s,.;:()\\-¿?¡!""\\\']+$'), django.core.validators.MinLengthValidator(20, message='La descripción debe tener al menos 20 caracteres.'), django.core.validators.MaxLengthValidator(2000, message='La descripción no puede superar los 2000 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='district',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El distrito solo puede contener letras, espacios y guiones.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s\\-]+$'), django.core.validators.MinLengthValidator(2, message='El distrito debe tener al menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[denuncias_service.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[denuncias_service.models.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='denunciaevidencia',
            name='file',
            field=models.FileField(upload_to='denuncias/evidencias/%Y/%m/%d/', validators=[denuncias_service.models.validate_file_size, denuncias_service.models.validate_file_extension]),
        ),
    ]
